

services:
  backend:
    build:
      context: ./shop-backend
      args:
        MONGO_URI: ${MONGO_URI}
        DB_NAME: ${DB_NAME}
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    networks:
      - shopnet

  ui:
    build:
      context: ./shop-ui
      args:
        NODE_VERSION: 18-alpine
        NODE_ENV: production
        UI_PORT: ${UI_PORT}
        HOSTNAME: 0.0.0.0
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL} 
    ports:
      - "${UI_PORT}:${UI_PORT}"
    restart: unless-stopped
    networks:
      - shopnet

networks:
  shopnet:
    driver: bridge
