export const ERROR = {
  ERROR_CODE: {
    ORGANIZATION_CREATION: 'ORG-FC',
    PATIENT_CREATION: 'PAT-FC',
    VITAL_NOT_FOUND: 'VIT-FC',
    USER_NOT_FOUND: 'USR-FC',
    OTP_GENERATION_FAILED: 'OTP-FC',
    PRESCRIPTION_NOT_FOUND: 'PRE-FC',
    ORG_NOT_FOUND: 'ORG-NF',
    PRACTITIONER_NOT_FOUND: 'PRACT-NF',
    TIMESLOT_NOT_FOUND: 'TS-NF',
    REFILL_REQ_FAILED: 'RE-FILL',
    ORGANIZATION_USER_CREATION: 'ORG_CR_ER',
    ORG_USER_CREATION: 'ORG-UR-CR',
    INVALID_CREDENTIALS: 'IV_CRE_ER',
    LOGIN_FAILED: 'LG-F',
    USER_CREATION: 'USR-NF',
    OTP_NOT_FOUND: 'OTP-NF',
    OTP_EXPIRED: 'OTP-EXP',
    INVALID_OTP: 'OTP-INV',
    USER_UPDATE_FAILED: 'USR-UPD-FC',
    USER_ALREADY_EXISTS: 'USR-AL-EX',
    SPECIALTY_NOT_FOUND: 'SPE-NF',
    ROLE_NOT_FOUND: 'ROL-NF',
    PRACTITIONER_CREATE_FAILED: 'PRACT-FC',
    PRACTITIONER_UPDATION: 'PRE-FF',
  },
  ERROR_MESSAGE: {
    ORGANIZATION_CREATION: 'Failed to create organization',
    PATIENT_CREATION: 'Failed to create patient',
    OTP_BLOCKED: 'Maximum OTP requests reached. Please try again after',
    OTP_UPDATE_FAILED: 'Failed to update OTP',
    OTP_GENERATION_FAILED: 'Failed to generate OTP',
    OTP_REQUEST_BLOCKED: (waitTime: number) =>
      `Please wait ${waitTime} seconds before requesting a new OTP`,
    USER_NOT_FOUND: 'User not found',
    VITAL_NOT_FOUND: 'Failed to fetch vitals',
    PRESCRIPTION_NOT_FOUND: 'Failed to create prescription',
    ORG_NOT_FOUND: 'Failed to fetch organization',
    PRACTITIONER_NOT_FOUND: 'Failed to fetch practitioner',
    TIMESLOT_NOT_FOUND: 'Time slot not found',
    REFILL_REQ_FAILED: 'Failed to reqest Refill',
    ORG_USER_CREATION: 'Failed to create organization user',
    INVALID_CREDENTIALS: 'Invalid email or password',
    LOGIN_FAILED: 'Login failed',
    USER_CREATION: 'Failed to create User',
    OTP_NOT_FOUND: 'OTP Not Found',
    OTP_EXPIRED: 'Otp Expired,',
    INVALID_OTP: 'Invalid OTP',
    MAX_OTP_LIMIT: 'You have reached the maximum OTP request limit',
    TRY_LATER: 'Try again later',
    USER_UPDATE_FAILED: 'Failed to update user',
    USER_ALREADY_EXISTS: 'User with this mobile number already exists.',
    PATIENT_ALREADY_EXISTS: 'This patient is already registered',
    SPECIALITY_NOT_FOUND: 'Failed to fetch speciality',
    ROLE_NOT_FOUND: 'Failed to fetch role',
    PRACTITIONER_CREATE_FAILED: 'Failed to create practitioner',
    PRACTITIONER_UPDATE: 'Failed to update practitioner',
  },
};

export const COMMON_ERROR = {
  INVALID_PHONE_NUMBER: 'Invalid phone number',
  INVALID_EMAIL: 'Invalid email address',
};

export const COMMON_ERROR_CODE = {
  INVALID_PHONE_NUMBER: 'IN-PN',
};
