export const SUCCESS = {
  SUCCESS_CODE: {
    ORGANIZATION_CREATION: 'ORG-CR',
    PATIENT_CREATION: 'PAT-CR',
    OTP_GENERATION: 'OTP-GEN',
    VITAL_FETCHED: 'VIT-GT',
    PRESCRIPTION_CREATION: 'PRE-CR',
    ORG_GET: 'ORG_GET',
    PRESCRIPTION_FETCHED: 'PRE-FT',
    PRESCRIPTION_UPDATED: 'PRE-UP',
    PRESCRIPTION_DEACTIVATED: 'PRE-DIS',
    PRACTITIONER_GET: 'PRACT-GT',
    GET_TIME_SLOT: 'GET_TS',
    REFILL_REQUESTED: 'RE-FILL',
    ORG_USER_CREATION: 'ORG_UR_CR_SUC',
    ORG_USER_GET: 'ORG_UR-FT',
    LOGIN_SUCCESS: 'LG-SUC',
    USER_CREATION: 'USE-CRE',
    OTP_VERIFIED: 'OTP-VER',
    SPECIALITY_FETCHED: 'SPE-FT',
    ROLE_FETCHED: 'ROL-FT',
    PRACTITIONER_CREATE: 'PRACT-CR',
    PRACTITIONER_UPDATION: 'PRE-UP',
    PASSWORD_RESET_SUCCESS: 'PRE-SUC',
  },
  SUCCESS_MESSAGE: {
    ORGANIZATION_CREATION: 'Organization created successfully',
    PATIENT_CREATION: 'Patient created successfully',
    OTP_GENERATION: 'OTP generated successfully',
    VITAL_FETCHED: 'Vitals fetched successfully',
    PRESCRIPTION_CREATION: 'Prescription created successfully',
    ORG_GET: 'Organization fetched',
    PRESCRIPTION_FETCHED: 'Prescription fetched successfully',
    PRESCRIPTION_UPDATED: 'Prescription updated successfully',
    PRESCRIPTION_DEACTIVATED: 'Prescription deactivated',
    PRACTITIONER_GET: 'Practitioner fetched successfully',
    GET_TIME_SLOT: 'Time slot fetched',
    REFILL_REQUESTED: 'Refill requested successfully',
    ORGANIZATION_USER_CREATION: 'Organization created successfully',
    ORG_USER_CREATION: 'Organization user created successfully',
    ORG_USER_GET: 'Organizations fetched successfully',
    LOGIN_SUCCESS: 'Login successful',
    USER_CREATION: 'User Created Successfully',
    OTP_VERIFIED: 'OTP Verified',
    SPECIALITY_FETCHED: 'Speciality fetched successfully',
    ROLE_FETCHED: 'Role fetched successfully',
    PRACTITIONER_CREATE: 'Practitioner created successfully',
    PRACTITIONER_UPDATION: 'Practitioner updated successfully',
    PASSWORD_RESET_SUCCESS: 'Password reset sucessfully',
  },
};
