name: Shop CI - Format, Lint, Build

on:
  pull_request:
    branches: [main]
    paths:
      - "shop-backend/**"
      - "shop-ui/**"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      ui: ${{ steps.filter.outputs.ui }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'shop-backend/**'
            ui:
              - 'shop-ui/**'

  backend:
    name: Shop Backend Checks
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    defaults:
      run:
        working-directory: shop-backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: npm run build

  ui:
    name: Shop UI Checks
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.ui == 'true'
    defaults:
      run:
        working-directory: shop-ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run lint
      - run: npm run build
